name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl matplotlib pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller excel_custom_filter_gui.py --onefile --noconsole

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: customfilter-win
          path: dist/excel_custom_filter_gui.exe
